# Generated by Django 4.1.2 on 2022-11-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_alter_qrcode_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('printed', 'Printed'), ('discarded', 'Discarded'), ('completed', 'Completed')], default='initial', help_text='Status of a Bar code', max_length=16)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='content',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('printed', 'Printed'), ('discarded', 'Discarded'), ('completed', 'Completed')], default='initial', help_text='Status of a QR code', max_length=16),
        ),
        migrations.CreateModel(
            name='TrayWithCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_storage_at', models.DateTimeField(null=True)),
                ('in_package_at', models.DateTimeField(null=True)),
                ('discarded_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('initial', 'Initial'), ('in-storage', 'Instorage'), ('in-package', 'Inpackage'), ('discarded', 'Discarded'), ('completed', 'Completed')], default='initial', help_text='Status of a tray', max_length=16)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray', to='qrapp.barcode')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tray', to='qrapp.qrcode')),
            ],
        ),
    ]
