# Generated by Django 4.1.2 on 2022-11-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_barcode_remove_qrcode_content_qrcode_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='uid',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
