# Generated by Django 4.1.2 on 2022-11-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0005_barcode_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='uid',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
