# Generated by Django 4.1.2 on 2022-11-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0006_alter_barcode_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='uid',
        ),
    ]
