# Generated by Django 4.1.2 on 2022-11-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0007_remove_barcode_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='printer name', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
